### ISSUE TITLE
Switch to port 587 for SMTP

### ISSUE THREAD

**Issue by taoeffect** [taoeffect/empress#24]
See comments in al3x/sovereign#318.

**Comment by bgw** [comment]
[This means we need to use STARTTLS](https://stackoverflow.com/questions/15796530/what-is-the-difference-between-ports-465-and-587).

**Comment by taoeffect** [comment]
Wow, didn't know that it required STARTTLS. OK, screw that then.

**Comment by bgw** [comment]
To clarify, it appears the issue is that people may misconfigure their mail client to allow a STARTTLS downgrade attack, whereas it's impossible to misconfigure smtps.
